from typing import List, Tuple

VERSION = "3.0.0"

L1_CATEGORIES: List[Tuple[str, str, str]] = [
    ("earnings_report", "Tulosraportti",
     "Säännölliset taloudelliset tulokset: osavuosikatsaukset, neljännesvuosi-, puolivuosi- ja tilinpäätöstiedotteet; voi sisältää tunnuslukuja, näkymiä ja lakisääteisiä raportteja."),
    ("share_buyback", "Omien osakkeiden osto",
     "Yhtiön omien osakkeiden takaisinostot: ohjelmien käynnistykset, jatkot, päivitykset ja päättämiset."),
    ("dividend", "Osinko",
     "Osinkoilmoitukset, ehdotukset, muutokset ja aikataulut (irtopäivä, täsmäytyspäivä, maksupäivä)."),
    ("agm_egm_governance", "Yhtiökokous & hallinto",
     "Varsinaisen tai ylimääräisen yhtiökokouksen kutsut ja tulokset; hallituksen nimitykset; yhtiöjärjestyksen muutokset; tilintarkastaja-asiat."),
    ("capital_raise_rights_issue", "Pääomanhankinta / Osakeanti",
     "Osakepohjainen rahoitus: merkintäoikeusannit, suunnatut annit, private placements, optio-/warranttiyksiköt; merkintätiedot ja pääoman käyttö."),
    ("pdmr_managers_transactions", "Johdon liiketoimet (PDMR)",
     "Johtohenkilöiden (PDMR) osakekaupat: ostot, myynnit, optioiden toteutukset."),
    ("admission_listing", "Listautuminen / Listasiirto",
     "Listautumiset ja kaupankäynnin aloittaminen: ensimmäinen kaupankäyntipäivä, listasiirrot, markkinapaikan muutokset."),
    ("debt_bond_issue", "Velka / Joukkovelkakirjat",
     "Velkarahoitus: joukkovelkakirjaemissiot, vaihtovelkakirjat, syndikoidut lainat, vihreät/sustainability-linkatut lainat."),
    ("mna", "Yritysjärjestelyt (M&A)",
     "Fuusiot, yritysostot, divestoinnit, jakautumiset, omaisuuden myynnit; sisältää ehdot, arvostukset ja aikataulut."),
    ("orders_contracts", "Tilaus / Sopimus",
     "Tilausvoitot, sopimusten myöntämiset, puitesopimukset, uusinnat, merkittävät tarjouskilpailut."),
    ("product_launch_partnership", "Tuote / Julkaisu / Kumppanuus",
     "Tuotteiden/palveluiden julkaisut ja päivitykset; kumppanuudet, yhteistyöt, yhteisyritykset, pilottihankkeet."),
    ("personnel_management_change", "Henkilöstö / Johtomuutokset",
     "Johto- ja hallitusmuutokset: nimitykset, eroamiset, väliaikaiset roolit, seuraajasuunnitelmat."),
    ("legal_regulatory_compliance", "Oikeudelliset / Sääntely / Compliance",
     "Oikeudenkäynnit, tutkimukset, sääntelyhyväksynnät tai -hylkäykset, sakot, vaatimustenmukaisuustiedot."),
    ("credit_ratings", "Luottoluokitukset",
     "Luottoluokituslaitosten antamat yhtiö- tai instrumenttiluokitukset; tarkkailulistat."),
    ("equity_actions_non_buyback", "Osaketoimet (ei takaisinosto)",
     "Osakesplitit/käänteissplitit, nimen- tai tickerin muutokset, konversiot, optioiden käyttö, osakelajien muutokset."),
    ("labor_workforce", "Työvoima",
     "Henkilöstöön liittyvät toimet: irtisanomiset, tuotantolaitosten sulkemiset, lakot/ammattiliittoasiat, suuret rekrytointisuunnitelmat."),
    ("incidents_controversies", "Tapaukset / Kiistat",
     "Operatiiviset tapaukset ja kiistat: onnettomuudet, kyberturvallisuusrikkomukset, tietosuojaongelmat, sanktiot."),
    ("admission_delisting", "Listalta poistaminen / Kaupankäynnin keskeytys",
     "Listalta poistot, kaupankäynnin keskeytykset, pörssitiedotteet, jotka vaikuttavat kaupankäyntiin."),
     ("rd_clinical_update", "T&K / Kliiniset ja tieteelliset päivitykset",
     "Kliiniset/prekliiniset ja tieteelliset tiedotteet: tutkimusten aloitukset ja virstanpylväät (FPI/LPI, rekrytointi), toplinetulokset (ensitiedot), kongressiabstraktit/posterit/suulliset esitykset, julkaisut, prekliiniset löydökset."),
    ("other_corporate_update", "Muut yhtiötiedotteet",
     "Yleiset yhtiöpäivitykset, jotka eivät sovi muihin kategorioihin; hallinnolliset tiedotteet.")
]
