from typing import List, Tuple

VERSION = "3.0.0"

L1_CATEGORIES: List[Tuple[str, str, str]] = [
    ("earnings_report", "Regnskabsmeddelelse",
     "Periodiske finansielle resultater: kvartals-, halvårs- og årsrapporter; kan indeholde nøgletal, fremtidskommentarer og lovpligtige oplysninger."),
    ("share_buyback", "Tilbagekøb af egne aktier",
     "Selskabets tilbagekøb af egne aktier: programlanceringer, forlængelser, opdateringer og afslutninger."),
    ("dividend", "Udbytte",
     "Udbytteerklæringer, forslag, ændringer og tidsplaner (ex-dato, registreringsdato, betalingsdato)."),
    ("agm_egm_governance", "Generalforsamling & Governance",
     "Indkaldelser og resultater fra ordinære/ekstraordinære generalforsamlinger; bestyrelses- og nomineringsspørgsmål; vedtægtsændringer; revisorforhold."),
    ("capital_raise_rights_issue", "Kapitalforhøjelse / Fortegningsemission",
     "Egenkapitalfinansiering: fortegningsemissioner, rettede emissioner, private placements, units/warrants; tegningsoplysninger og anvendelse af provenu."),
    ("pdmr_managers_transactions", "Ledelsens handler (PDMR)",
     "Handler foretaget af personer i ledende stillinger (PDMR): køb, salg, optionsudnyttelse."),
    ("admission_listing", "Børsnotering / Optagelse til handel",
     "Optagelse til handel: første handelsdag, opnoteringer, ændring af handelsplads."),
    ("debt_bond_issue", "Obligation / Gældsudstedelse",
     "Gældsfinansiering: obligationsudstedelser, konvertible lån, syndikerede lån, grønne/sustainability-obligationer."),
    ("mna", "Fusioner & Opkøb (M&A)",
     "Fusioner, opkøb, frasalg, spaltninger, aktivsalg; inkluderer vilkår, værdiansættelser og tidslinjer."),
    ("orders_contracts", "Ordre / Kontrakt",
     "Ordrevindinger, kontrakttildelinger, rammeaftaler, fornyelser, vigtige udbudsresultater."),
    ("product_launch_partnership", "Produkt / Lancering / Partnerskab",
     "Produkt- og servicelanceringer og opgraderinger; partnerskaber, samarbejder, joint ventures, pilotprojekter."),
    ("personnel_management_change", "Personale / Ledelsesændringer",
     "Ændringer i direktion og bestyrelse: udnævnelser, fratrædelser, midlertidige roller, succession."),
    ("legal_regulatory_compliance", "Juridisk / Regulatorisk / Compliance",
     "Retssager, undersøgelser, regulatoriske godkendelser/afslag, bøder, compliance-oplysninger."),
    ("credit_ratings", "Kreditvurderinger",
     "Ratingændringer af selskaber eller instrumenter fra kreditvurderingsbureauer; observationslister."),
    ("equity_actions_non_buyback", "Aktietiltag (ikke tilbagekøb)",
     "Aktiesplit/reversesplit, ændringer af navn eller ticker, konverteringer, optionsudnyttelse, ændringer i aktieklasser."),
    ("labor_workforce", "Arbejdskraft",
     "Tiltag vedrørende arbejdsstyrken: afskedigelser, fabriksnedlæggelser, strejker/fagforeningsforhold, store rekrutteringsplaner."),
    ("incidents_controversies", "Hændelser / Kontroverser",
     "Operationelle hændelser og kontroverser: ulykker, cybersikkerhedsbrud, data-/privatlivshændelser, sanktioner."),
    ("admission_delisting", "Afnotering / Handelsstop",
     "Afnoteringer, handelsstandsninger, børsmeddelelser med betydning for handel."),
    ("other_corporate_update", "Øvrige selskabsopdateringer",
     "Generelle selskabsmeddelelser, der ikke passer i de øvrige kategorier; administrative bekendtgørelser.")
]
