from typing import List, Tuple

VERSION = "3.0.0"

L1_CATEGORIES: List[Tuple[str, str, str]] = [
    ("earnings_report", "Delårsrapport / Årsredovisning",
     "Periodiska finansiella resultat: delårsrapporter, kvartalsrapporter, halvårsrapporter, bokslut; kan inkludera nyckeltal, framtidskommentarer, och lagstadgade redovisningar."),
    ("share_buyback", "Aktieåterköp",
     "Bolagets återköp av egna aktier: lansering av program, förlängningar, uppdateringar, avslut."),
    ("dividend", "Utdelning",
     "Utdelningsbesked, förslag, ändringar, tidplaner (avstämningsdag, utbetalningsdag)."),
    ("agm_egm_governance", "Bolagsstämma & styrning",
     "Kallelser och resultat från årsstämma/extra bolagsstämma; styrelse- och valberedningsfrågor; stadgeändringar; revisorsärenden."),
    ("capital_raise_rights_issue", "Kapitalanskaffning / Företrädesemission",
     "Egetkapitalfinansiering: företrädesemissioner, riktade emissioner, private placements, units/teckningsoptioner; teckningsdetaljer och användning av kapitalet."),
    ("pdmr_managers_transactions", "Insynshandel (PDMR)",
     "Transaktioner av personer i ledande ställning (PDMR): köp, försäljningar, optionsinlösen."),
    ("admission_listing", "Notering / Listbyte",
     "Noteringar och upptagande till handel: första handelsdag, listbyten, byte av handelsplats."),
    ("debt_bond_issue", "Obligation / Skuldfinansiering",
     "Skuldfinansiering: emission av obligationer/lån, konvertibler, syndikerade lån, gröna/sustainability-länkar."),
    ("mna", "Företagsaffärer (M&A)",
     "Fusioner, förvärv, avyttringar, avknoppningar, tillgångsförsäljningar; inkluderar villkor, värderingar, tidslinjer."),
    ("orders_contracts", "Order / Kontrakt",
     "Ordervinster, kontraktstilldelningar, ramavtal, förnyelser, viktiga upphandlingar."),
    ("product_launch_partnership", "Produkt / Lansering / Partnerskap",
     "Lanseringar och uppgraderingar av produkter/tjänster; partnerskap, samarbeten, joint ventures, pilotprojekt."),
    ("personnel_management_change", "Personal / Ledningsförändringar",
     "Förändringar i ledning och styrelse: tillsättningar, avgångar, tillfälliga roller, successionsplaner."),
    ("legal_regulatory_compliance", "Juridik / Reglering / Compliance",
     "Tvister, utredningar, regulatoriska godkännanden/avslag, böter/sanktioner, regelefterlevnadsrapporter."),
    ("credit_ratings", "Kreditbetyg",
     "Ratingåtgärder för bolag eller instrument från kreditvärderingsinstitut; bevakningslistor."),
    ("equity_actions_non_buyback", "Aktieåtgärder (ej återköp)",
     "Aktiesplit/reversesplit, namn- eller tickerändringar, konverteringar, optionsinlösen, förändringar i aktieslag."),
    ("labor_workforce", "Arbetskraft / Personal",
     "Åtgärder kring arbetsstyrkan: uppsägningar, fabriksnedläggningar, strejker/fackliga frågor, större rekryteringsplaner."),
    ("incidents_controversies", "Incidenter / Kontroverser",
     "Operativa incidenter: olyckor, cybersäkerhetsintrång, data-/integritetsincidenter, sanktioner."),
    ("admission_delisting", "Avnotering / Handelsstopp",
     "Avnoteringar, handelsstopp/uppehåll, börsmeddelanden som påverkar handel."),
     ("rd_clinical_update", "FoU / Klinisk & vetenskaplig uppdatering",
     "Kliniska/prekli­niska och vetenskapliga uppdateringar: studiestarter och milstolpar (FPI/LPI, rekrytering), topline-resultat/avläsningar, kongressabstrakt/posters/muntliga presentationer, publikationer, prekliniska fynd."),
    ("other_corporate_update", "Övrig bolagsinformation",
     "Allmänna bolagsuppdateringar som inte passar in i övriga kategorier; administrativa meddelanden.")
]
