version: 1
defaults:
  min_amount_ccy: SEK
  company_tier_weights: { "mega": 1.0, "large": 0.8, "mid": 0.6, "small": 0.4 }
  source_weights: { "exchange": 1.0, "issuer_pr": 0.8, "regulator": 1.0, "wire": 0.6 }

events:
  - key: guidance_change
    label: Guidance change for company or competitor
    thresholds:
      revenue_pct_abs: 5           # >= 5% change is significant
    patterns:
      any: ["guidance", "outlook", "prognos", "prognosis", "raises guidance", "sänker prognosen"]
    score:
      base: 0.7
      features: ["pct_change", "source_weight", "company_tier"]

  - key: equity_raise
    label: Equity raise
    thresholds:
      amount_ccy: 50000000         # >= 50M SEK
    patterns:
      any: ["företrädesemission", "riktad emission", "new share issue", "private placement", "prospekt"]
    score:
      base: 0.65
      features: ["amount_log", "source_weight", "novelty_30d"]

  - key: ceo_change
    label: CEO change
    thresholds: {}
    patterns:
      any: ["CEO", "vd", "verkställande direktör", "chief executive"]
    score:
      base: 0.6
      features: ["source_weight", "company_tier"]

  - key: regulatory_approval
    label: Regulatory approval/clearance/refusal
    thresholds: {}
    patterns:
      any: ["approved", "clearance", "godkänd", "CE mark", "CRL", "refusal", "återkallelse", "recall"]
    score:
      base: 0.7
      features: ["source_weight", "corroboration_count"]

  - key: phase_3_clinical_trial_results
    label: Phase 3 clinical trial results
    thresholds: {}
    patterns:
      any: []
    score:
      base: 0.7
      features: ["source_weight", "corroboration_count"]

  - key: last_day_trading_of_rights
    label: Last day that rights are traded in rights issue, if stock was preassured from rights selling
    thresholds: {}
    patterns:
      any: []
    score:
      base: 0.7
      features: ["source_weight", "corroboration_count"]

  - key: incentive_program_expiration_upcoming
    label: Incentive programs expiring in next 3 months can lead to positive (possibly negative) communication
    thresholds: {}
    patterns:
      any: []
    score:
      base: 0.7
      features: ["source_weight", "corroboration_count"]

  - key: supplier_shortage
    label: Shortage at a supplier might lead to supply chain issues
    thresholds: {}
    patterns:
      any: []
    score:
      base: 0.7
      features: ["source_weight", "corroboration_count"]

  - key: distributor_inventory_build
    label: Inventory build up at distributor might lead to future sales drop
    thresholds: {}
    patterns:
      any: []
    score:
      base: 0.7
      features: ["source_weight", "corroboration_count"]
            
  - key: major_product_recall
    label: companies recalling a major product might increase cost and drop sales and also lawsuits
    thresholds: {}
    patterns:
      any: []
    score:
      base: 0.7
      features: ["source_weight", "corroboration_count"]
  
  - key: factory_shutdown
    label: Shutdown of capacity from accidents or other reasons leads might lead to supply issues
    thresholds: {}
    patterns:
      any: []
    score:
      base: 0.7
      features: ["source_weight", "corroboration_count"]

  - key: top_tier_partnerships
    label: Unproven company/product recognition by a top tier partnership
    thresholds: {}
    patterns:
      any: []
    score:
      base: 0.7
      features: ["source_weight", "corroboration_count"]
  
  - key: major_order_win
    label: Major order win from established top tier customer
    thresholds: {}
    patterns:
      any: []
    score:
      base: 0.7
      features: ["source_weight", "corroboration_count"]
      
  - key: competitor_tender_offer
    label: A competitor recieves tender offer for entire business
    thresholds: {}
    patterns:
      any: []
    score:
      base: 0.7
      features: ["source_weight", "corroboration_count"]

  - key: lawsuit_filed
    label: A regulator starts investigation or a lawsuit is filed against the company
    thresholds: {}
    patterns:
      any: []
    score:
      base: 0.7
      features: ["source_weight", "corroboration_count"]

  - key: large_share_buyback_program
    label: A large share buyback program might support the share price. Needs to be a fresh initiation or an acceleration.
    thresholds: {}
    patterns:
      any: []
    score:
      base: 0.7
      features: ["source_weight", "corroboration_count"]

  - key: tending_period_expires
    label: Tendering period expires might be higher risk for the share if not 90% is reached
    thresholds: {}
    patterns:
      any: []
    score:
      base: 0.7
      features: ["source_weight", "corroboration_count"]
